stack["anup"]
stack["amit"]
stack["arjun"]
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop)
print(stack)
print(stack.pop())
print(stack)
