stack["anup"]
stack["at"]
stack["arjun"]
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)
print(stack.pop)
print(stack)
print(stack.pop())
print(stack)
